### ISSUE TITLE
[FEATURE]: Unit Test Coverage of our Django API Endpoints

### ISSUE THREAD

**Issue by karkir0003** [DSGT-DLP/Deep-Learning-Playground#1059]
### Feature Name

Unit Test for Django APIs

### Your Name

Karthik Subramanian

### Description

Writing unit tests with `pytest` for our Django API Endpoints

Loosely part of this project: https://www.notion.so/9b6766cea0b24060bb10d806d58ee0c1?v=1c2cddea700a478a86e95a5e86c09cf8&p=89819d36b0544586a6c2d3cf38fa5f9a&pm=s

```[tasklist]
### Tasks
- [x] Unit test for /columns endpoint
- [ ] Unit test for /tabular train endpoint
- [ ] Unit test for /image train endpoint
- [ ] Ensure that pytest is running for training/ unit tests
```
