### ISSUE TITLE
Implement Classical ML Training Flow

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#750]
**Describe the solution you'd like**
Implement/modify the backend endpoints & UI needed to create a Classical ML trainspace.

**Additional context**
This should have about the same folder structure as Tabular: All Classical ML specific code should be in src/features/Train/features/ClassicalML, split the code into components, constants, redux, types folders, etc.
There are existing layout components in src/features/Train/components that would be helpful in creating the actual UI components for Classical ML.
Existing train constants should be modified also to allow for an Classical ML trainspace selection.
Make sure to modularize Classical ML also by adding an index file to handle exporting of elements outside of Classical ML (Tabular also has an example of this).
Please ask questions if you have any, especially for this feature (since I made some opinionated decisions on the structure of the train code on the frontend that should either be kept or changed to maintain consistency)!

**Setup Instructions (what branch to work off of)**
Run the following commands
```
git checkout nextjs
git pull origin nextjs
git checkout -b classical-ml-train
```
FYI: If you are not able to immediately run `git checkout nextjs`, make sure you commit your changes in the current branch or run `git stash` and then execute the above commands

```[tasklist]
### Tasks
- [ ] Implement Frontend for Classical ML Trainspace. This should be its own PR
- [ ] Implement Backend endpoints in Django (/training directory) for Classical ML Trainspace. This should be its own PR
- [ ] Test that the flow works and that the user can select the various buttons
```

**Comment by karkir0003** [comment]
ETA:
middle of the week first PR (frontend)

**Comment by karkir0003** [comment]
@AmyCGT what's the ETA looking like on this task?

**Comment by noah-iversen** [comment]
@karkir0003 reviving this thread because it ties directly to Classical ML doc. Should probably have more specific UI/backend tickets though

**Comment by karkir0003** [comment]
> @karkir0003 reviving this thread because it ties directly to Classical ML doc. Should probably have more specific UI/backend tickets though

sounds good @noah-iversen . we can work off of the tickets you'll create. let's get some solid momentum going on this :)
