### ISSUE TITLE
[FEATURE]: Refactor the rest of the backend training endpoints to /training

### ISSUE THREAD

**Issue by dwu359** [DSGT-DLP/Deep-Learning-Playground#908]
### Feature Name

Refactor the rest of the backend training endpoints to /training

### Your Name

Daniel Wu

### Description

Add endpoints to /training so that:

- /image trains an image model
- /object-detection trains an object detection model
- /classical-ml trains a classical-ML model

Make sure to update, reuse, and/or add any classes in /core as necessary
```[tasklist]
### Tasks
- [ ] https://github.com/DSGT-DLP/Deep-Learning-Playground/issues/993
- [ ] https://github.com/DSGT-DLP/Deep-Learning-Playground/issues/994
- [ ] https://github.com/DSGT-DLP/Deep-Learning-Playground/issues/750
```
